FROM python:3.11-slim
WORKDIR /app
COPY requirements-backend.txt .
RUN pip install --no-cache-dir -r requirements-backend.txt
COPY src/api ./src/api
COPY src/models ./src/models
COPY src/preprocessing ./src/preprocessing
COPY artifacts ./artifacts
EXPOSE 8000
CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
